// Generated by CoffeeScript 1.6.3
(function() {
  var Config, Conjuntas, Index, LocalStrategy, Login, app, express, http, newrelic, passport, path, port;

  express = require('express');

  http = require('http');

  path = require('path');

  passport = require('passport');

  LocalStrategy = require('passport-local').Strategy;

  newrelic = require('newrelic');

  Config = require('./config')();

  Index = require('./controllers/Index');

  Conjuntas = require('./controllers/Conjuntas');

  Login = require('./controllers/Login');

  app = express();

  app.set('views', path.join(__dirname, 'views'));

  app.set('view engine', 'jade');

  app.use(express.favicon());

  app.use(express.logger('dev'));

  app.use(express.json());

  app.use(express.urlencoded());

  app.use(express.methodOverride());

  app.use(express.cookieParser('bfc'));

  app.use(express.session());

  app.use(app.router);

  app.use(express["static"](path.join(__dirname, 'public')));

  if ('development' === app.get('env')) {
    app.use(express.errorHandler());
  }

  /*GET Operations*/


  app.get('/', Index.index);

  app.get('/login', Index.index);

  app.get('/conjuntas', Conjuntas.findAllOpened);

  app.get('/conjuntas/abiertas', Conjuntas.findAllOpened);

  app.get('/conjuntas/cerradas', Conjuntas.findAllClosed);

  app.get('/conjuntas/nueva', Conjuntas.formNewConjunta);

  app.get('/conjuntas/ultimas', Conjuntas.findLatestClosed);

  app.get('/conjuntas/:id', Conjuntas.findById);

  /*POST Operations*/


  app.post('/conjuntas', Conjuntas.addConjunta);

  app.post('/login', Login.login);

  /*PUT Operations*/


  app.put('/conjuntas/:id', Conjuntas.updateConjunta);

  /*DELETE Operations*/


  app["delete"]('/conjuntas/:id', Conjuntas.deleteConjunta);

  port = process.env.PORT || Config.port;

  http.createServer(app).listen(port, function() {
    console.log('Express server listening on port ' + port);
  });

}).call(this);
