// Generated by CoffeeScript 1.6.3
(function() {
  var ConjuntaModel, mongoose;

  mongoose = require('mongoose');

  ConjuntaModel = mongoose.model('Conjunta');

  exports.findAllOpened = function(req, res) {
    console.log(req.params + " " + req.params);
  };

  exports.findAllClosed = function(req, res) {
    console.log(req.params + " " + req.params);
  };

  exports.findById = function(req, res) {
    console.log(req.params + " " + req.params);
  };

  exports.findLatestClosed = function(req, res) {
    console.log(req.params + " " + req.params);
  };

  exports.formNewConjunta = function(req, res) {
    console.log(req.params + " " + req.params);
  };

  exports.addConjunta = function(req, res) {
    console.log(req.params + " " + req.params);
  };

  exports.updateConjunta = function(req, res) {
    console.log(req.params + " " + req.params);
  };

  exports.deleteConjunta = function(req, res) {
    console.log(req.params + " " + req.params);
  };

}).call(this);
