// Generated by CoffeeScript 1.6.3
(function() {
  var UserModel, mongoose;

  mongoose = require('mongoose');

  UserModel = require('../models/UserModel');

  module.exports = function(passport) {
    passport.use(UserModel.createStrategy());
    passport.serializeUser(UserModel.serializeUser());
    passport.deserializeUser(UserModel.deserializeUser());
  };

}).call(this);
