// Generated by CoffeeScript 1.6.3
(function() {
  var Db, Server, coleccion, config, db, mongo, server;

  config = require('../config')();

  mongo = require('mongodb');

  Server = mongo.Server;

  Db = mongo.Db;

  coleccion = 'prueba';

  server = new Server(config.mongo.host, config.mongo.port, {
    auto_reconnect: true,
    safe: false
  });

  db = new Db(config.mongo.bbdd, server);

  db.open(function(err, db) {
    if (!err) {
      console.log("Conectado");
      db.authenticate('roto2', 'gloriaroto2', function(err, res) {
        if (!err) {
          console.log("Autenticado: " + res);
        }
      });
    }
  });

  exports.findAllOpened = function(req, res) {
    db.collection(coleccion, {
      safe: true
    }, function(err, collection) {
      if (!err) {
        collection.find({}).toArray(function(err, items) {
          if (!err) {
            res.json(items);
          }
        });
      }
    });
  };

  exports.findAllClosed = function(req, res) {
    db.collection(coleccion, {
      safe: true
    }, function(err, collection) {
      if (!err) {
        collection.find({
          'estado': 'cerrada'
        }).toArray(function(err, items) {
          if (!err) {
            console.log(items);
            res.json(items);
          }
        });
      }
    });
  };

  exports.findById = function(req, res) {
    console.log(req.params + " " + req.params);
  };

  exports.findLatestClosed = function(req, res) {
    console.log(req.params + " " + req.params);
  };

  exports.formNewConjunta = function(req, res) {
    res.render('conjuntas/form_nueva_conjunta', {
      title: 'Nueva conjunta'
    });
  };

  exports.addConjunta = function(req, res) {
    db.collection(coleccion, {
      safe: true
    }, function(err, collection) {
      if (!err) {
        collection.insert({
          nombre: req.param('nombre'),
          amazon: req.param('link')
        }, function(err, data) {
          if (!err) {
            res.render('conjuntas/nueva_conjunta', {
              title: 'Nueva conjunta ' + req.param('link') + ' insertada'
            });
            console.log(data);
          }
        });
      }
    });
  };

  exports.updateConjunta = function(req, res) {
    console.log(req.params + " " + req.params);
  };

  exports.deleteConjunta = function(req, res) {
    console.log(req.params + " " + req.params);
  };

}).call(this);
