// Generated by CoffeeScript 1.6.3
(function() {
  var conjuntas_view, login_view;

  conjuntas_view = 'index';

  login_view = 'users/login';

  exports.index = function(req, res) {
    if (req.user) {
      res.render(conjuntas_view, {
        title: 'Passport Setup',
        user: req.user
      });
    } else {
      res.render(login_view, {
        title: 'Login',
        message: req.flash('error'),
        user: req.user
      });
    }
  };

}).call(this);
