// Generated by CoffeeScript 1.6.3
(function() {
  var User, conjuntas_view, login_view, main_ruta, mongoose, registro_view, user_view;

  mongoose = require('mongoose');

  User = require('../models/User');

  login_view = 'users/login';

  registro_view = 'users/registro';

  conjuntas_view = 'index';

  main_ruta = '/';

  user_view = 'users/show';

  /*Registrar usuario GET*/


  exports.registro = function(req, res) {
    if (req.user) {
      res.redirect(main_ruta);
    } else {
      res.render(registro_view, {
        title: 'Registrarse',
        user: new User()
      });
    }
  };

  /*Registrar usuario POST*/


  exports.create = function(req, res) {
    User.register(new User({
      email: req.body.email,
      nickname: req.body.nickname
    }), req.body.password, function(err, user) {
      if (err) {
        res.render(registro_view, {
          msg: err.message
        });
      }
      res.render(conjuntas_view, {
        user: user
      });
    });
  };

  /*Mostrar usuario GET*/


  exports.user = function(req, res, next, id) {
    User.findOne({
      _id: id
    }).exec(function(err, user) {
      if (err) {
        return next(err);
      }
      if (!user) {
        return next(new Error('Fallo cargando el usuario ' + id));
      }
      req.profile = user;
      next();
    });
  };

}).call(this);
