// Generated by CoffeeScript 1.6.3
(function() {
  var UserModel, conjuntas_view, login_view, main_ruta, registro_view, user_view;

  UserModel = require('../../models/UserModel');

  /*Rutas*/


  main_ruta = '/';

  /*Vistas*/


  login_view = 'users/login';

  registro_view = 'users/registro';

  conjuntas_view = 'index';

  user_view = '../users/show';

  exports.createUser = function(req, res) {
    console.log(req.body.repeat_password === req.body.password);
    if (req.body.repeat_password !== req.body.password) {
      res.render(registro_view, {
        msg: 'Las contraseñas no coinciden'
      });
    } else {
      UserModel.register(new UserModel({
        email: req.body.email,
        nickname: req.body.nickname
      }), req.body.password, function(err, user) {
        if (err) {
          res.render(registro_view, {
            msg: err.message
          });
        }
        if (user) {
          res.render(conjuntas_view, {
            user: user
          });
        }
      });
    }
  };

  exports.renderForm = function(req, res) {
    if (req.user && req.user.active === true) {
      res.redirect(main_ruta);
    } else {
      res.render(registro_view, {
        title: 'Registrarse',
        user: new UserModel()
      });
    }
  };

  exports.findByUsername = function(req, res) {
    UserModel.findByUsername(req.params.user, function(err, user) {
      if (err) {
        res.render(conjuntas_view);
      }
      if (user) {
        res.render(conjuntas_view, {
          user: user
        });
      }
    });
  };

}).call(this);
