// Generated by CoffeeScript 1.6.3
(function() {
  var LoginService, UserModel, conjuntas_view, login_view, main_ruta, password_not_match, registro_view, user_view;

  UserModel = require('../../models/UserModel');

  LoginService = require('../Login/LoginService');

  main_ruta = '/';

  login_view = 'users/login';

  registro_view = 'users/registro';

  user_view = 'users/show';

  conjuntas_view = 'index';

  password_not_match = 'Las contraseñas no coinciden';

  exports.createUser = function(req, res) {
    if (req.body.repeat_password !== req.body.password) {
      return res.render(registro_view, {
        msg: password_not_match
      });
    } else {
      return UserModel.register(new UserModel({
        email: req.body.email,
        nickname: req.body.nickname
      }), req.body.password, function(err, user) {
        if (err) {
          res.render(registro_view, {
            msg: err.message
          });
        }
        if (user) {
          return res.render(conjuntas_view, {
            user: user
          });
        }
      });
    }
  };

  exports.renderForm = function(req, res) {
    var activo;
    activo = LoginService.isLogged(req);
    if (activo === true) {
      return res.redirect(main_ruta);
    } else {
      return res.render(registro_view, {
        title: 'Registrarse',
        user: new UserModel()
      });
    }
  };

  exports.findByUsername = function(req, res) {
    return UserModel.findByUsername(req.params.user, function(err, user) {
      if (err) {
        res.render(conjuntas_view);
      }
      if (user) {
        return res.render(conjuntas_view, {
          user: user
        });
      }
    });
  };

}).call(this);
