// Generated by CoffeeScript 1.6.3
(function() {
  var LoginService, conjuntas_view, login_view, selectData, selectView;

  LoginService = require('../Login/LoginService');

  conjuntas_view = 'index';

  login_view = 'users/login';

  exports.index = function(req) {
    var activo, arrayDatos, datos, vista;
    activo = LoginService.isLogged(req);
    arrayDatos = new Array();
    vista = selectView(activo);
    datos = selectData(req, activo);
    arrayDatos.push(vista);
    arrayDatos.push(datos);
    return arrayDatos;
  };

  selectView = function(activo) {
    if (activo === true) {
      return conjuntas_view;
    } else {
      return login_view;
    }
  };

  selectData = function(req, activo) {
    var datos;
    if (activo === true) {
      datos = {
        title: 'Passport Setup',
        user: req.user
      };
    } else {
      datos = {
        title: 'Login',
        message: req.flash('error'),
        user: req.user
      };
    }
    return datos;
  };

}).call(this);
