// Generated by CoffeeScript 1.6.3
(function() {
  var config;

  config = {
    local: {
      mode: 'dev',
      port: 3000,
      mongo: {
        host: 'localhost',
        port: 27017,
        bbdd: 'heroku_app19057649'
      }
    },
    pre: {
      mode: 'pre',
      port: 4000,
      mongo: {
        host: 'localhost',
        port: 27017,
        bbdd: 'heroku_app19057649'
      }
    },
    pro: {
      mode: 'pro',
      port: 5000,
      mongo: {
        host: 'ds053128.mongolab.com',
        port: 53128,
        bbdd: 'heroku_app19057649'
      }
    }
  };

  module.exports = function(mode) {
    return config[mode || process.argv[2] || 'dev'] || config.local;
  };

}).call(this);
