// Generated by CoffeeScript 1.6.3
(function() {
  var LocalStrategy, User, mongoose;

  mongoose = require('mongoose');

  LocalStrategy = require('passport-local').Strategy;

  User = mongoose.model('User');

  module.exports = function(passport) {
    passport.use(User.createStrategy());
    passport.serializeUser(User.serializeUser());
    passport.deserializeUser(User.deserializeUser());
  };

}).call(this);
