// Generated by CoffeeScript 1.6.3
(function() {
  var conjuntas_page, login_page, login_view, selectDatos, selectMode, selectView;

  login_view = 'users/login';

  conjuntas_page = '/';

  login_page = 'login';

  exports.signin = function() {
    return conjuntas_page;
  };

  exports.login = function(req) {
    var activo, arrayDatos, datos, modo, vista;
    activo = this.isLogged(req);
    arrayDatos = new Array();
    modo = selectMode(req, activo);
    vista = selectView(activo);
    datos = selectDatos(req, activo);
    arrayDatos.push(modo);
    arrayDatos.push(vista);
    arrayDatos.push(datos);
    return arrayDatos;
  };

  exports.logout = function(req) {
    req.logout();
    return login_page;
  };

  exports.isLogged = function(req) {
    return req.user && req.user.active === true;
  };

  selectView = function(activo) {
    if (activo === true) {
      return conjuntas_page;
    } else {
      return login_view;
    }
  };

  selectDatos = function(req, activo) {
    var datos;
    if (activo === true) {
      datos = {
        title: 'Login'
      };
    } else {
      datos = {
        title: 'Login',
        message: req.flash('Error'),
        user: req.user
      };
    }
    return datos;
  };

  selectMode = function(req, activo) {
    if (activo === true) {
      return 'redirect';
    } else {
      return 'render';
    }
  };

}).call(this);
