// Generated by CoffeeScript 1.6.3
(function() {
  var conjuntas_view, login_view;

  login_view = 'users/login';

  conjuntas_view = '/';

  /*Login POST*/


  exports.signin = function(req, res) {
    res.redirect('/');
  };

  /*Login GET*/


  exports.login = function(req, res) {
    if (req.user && req.user.active === true) {
      res.redirect(conjuntas_view);
    } else {

      res.render(login_view, {
        title: 'Login',
        message: req.flash('Error'),
        user: req.user
      });
    }
  };

  /*Logout GET*/


  exports.logout = function(req, res) {
    req.logout();
    res.redirect('login');
  };

}).call(this);
