// Generated by CoffeeScript 1.6.3
(function() {
  var ConjuntasSerive;

  ConjuntasSerive = require('../services/Conjuntas/ConjuntasService');

  exports.findAllOpened = function(req, res) {
    ConjuntasSerive.findAllOpened(req, res);
  };

  exports.findAllClosed = function(req, res) {
    ConjuntasSerive.findAllClosed(req, res);
  };

  exports.findById = function(req, res) {
    ConjuntasSerive.findById(req, res);
  };

  exports.findLatestClosed = function(req, res) {
    ConjuntasSerive.findLatestClosed(req, res);
  };

  exports.formNewConjunta = function(req, res) {
    ConjuntasSerive.formNewConjunta(req, res);
  };

  exports.addConjunta = function(req, res) {
    ConjuntasSerive.addConjunta(req, res);
  };

  exports.updateConjunta = function(req, res) {
    ConjuntasSerive.updateConjunta(req, res);
  };

  exports.deleteConjunta = function(req, res) {
    ConjuntasSerive.deleteConjunta(req, res);
  };

}).call(this);
