// Generated by CoffeeScript 1.6.3
(function() {
  var HomeService;

  HomeService = require('../services/Home/HomeService');

  exports.index = function(req, res) {
    var datosVista;
    datosVista = new Array();
    datosVista = HomeService.index(req);
    return res.render(datosVista[0], datosVista[1]);
  };

}).call(this);
