// Generated by CoffeeScript 1.6.3
(function() {
  var HomeService;

  HomeService = require('../services/Home/HomeService');

  exports.index = function(req, res) {
    HomeService.index(req, res);
  };

}).call(this);
