// Generated by CoffeeScript 1.6.3
(function() {
  var LoginService;

  LoginService = require('../services/Login/LoginService');

  exports.signin = function(req, res) {
    var vista;
    vista = LoginService.signin;
    return res.redirect(vista);
  };

  exports.login = function(req, res) {
    var arrayDatos;
    arrayDatos = new Array;
    arrayDatos = LoginService.login(req);
    if (arrayDatos[0] === 'redirect') {
      return res.redirect(arrayDatos[1]);
    } else {
      return res.render(arrayDatos[1], arrayDatos[2]);
    }
  };

  exports.logout = function(req, res) {
    var vista;
    vista = LoginService.logout(req);
    return res.redirect(vista);
  };

}).call(this);
