// Generated by CoffeeScript 1.6.3
(function() {
  var LoginService;

  LoginService = require('../services/Login/LoginService');

  /*Login POST*/


  exports.signin = function(req, res) {
    LoginService.signin(req, res);
  };

  /*Login GET*/


  exports.login = function(req, res) {
    LoginService.login(req, res);
  };

  /*Logout GET*/


  exports.logout = function(req, res) {
    LoginService.logout(req, res);
  };

}).call(this);
