// Generated by CoffeeScript 1.6.3
(function() {
  describe("Configuration Setup", function() {
    it("Debe cargar configuracion para entorno de desarrollo", function(next) {
      var config;
      config = require('.')();
      expect(config.mode).toBe('dev');
      return next();
    });
    it("Debe cargar configuracion para entorno PRE", function(next) {
      var config;
      expect(config.mode).toBe('pre');
      config = require('.')('pre');
      return next();
    });
    return it("Debe cargar configuracion para entorno PRO", function(next) {
      var config;
      expect(config.mode).toBe('pro');
      config = require('.')('pro');
      return next();
    });
  });

}).call(this);
